apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace:  {{ .Release.Namespace }}
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /home/wso2carbon/wso2am-4.1.0.47/repository/logs/*.log   ## A variabiliser
    include_lines: ['(apimMetrics):']
    output.logstash:
        hosts: ["digest.grash-cmms.com/beats"]   ### A variabiliser